{{- if .Values.env.configSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.configSecret.name }}
  labels:
    app: {{ include "student-service.name" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.env.configSecret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}