apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-service
  labels:
    app: courses-service
spec:
  selector:
    matchLabels:
      app: courses-service
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: courses-service
    spec:
      containers:
        - name: courses-service
          image: thanhnb1/courses-service:latest
          env:
          - name: SERVER_PORT
            value: "8080"
          - name: MYSQL_URL
            value: "jdbc:mysql://mysql:3306/courses"
          - name: MYSQL_USERNAME
            value: "courses"
          - name: MYSQL_PASSWORD
            value: "VNTechies2023"

          # 1. Cấu hình URI gọi đến Students service. Trong thực tế sẽ cấu hình đến Object Service trong Kubernetes
          # nhưng vì chưa tìm hiểu đến object Service này (sẽ tìm hiểu trong bài sau) nên sẽ để IP và PORT của pod.
          # - name: STUDENTS_URI
          #   value: http://10.1.28.78:8080

          # 2. Cấu hình URI gọi đến Students service. Thường sẽ sử dụng DNS của service để cấu hình
          # vì IP và port của service vẫn có thể thay đổi.
          # - name: STUDENTS_URI
          #   value: http://10.152.183.232:80

          # 3. Cấu hình URI gọi đến Students service sử dụng DNS của service.
          - name: STUDENTS_URI
            value: http://students-service
          ports:
            - containerPort: 8080
      restartPolicy: Always