---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE USER 'students'@'%' IDENTIFIED BY 'VNTechies2023';
    CREATE DATABASE students CHARACTER SET utf8 COLLATE utf8_general_ci;
    GRANT ALL ON students.* TO 'students'@'%';
    flush privileges;

    CREATE USER 'courses'@'%' IDENTIFIED BY 'VNTechies2023';
    CREATE DATABASE courses CHARACTER SET utf8 COLLATE utf8_general_ci;
    GRANT ALL ON courses.* TO 'courses'@'%';
    flush privileges;
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: VNTechies2023
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        emptyDir:
          sizeLimit: 1Gi
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config