apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-service
  labels:
    app: students-service
spec:
  selector:
    matchLabels:
      app: students-service
  replicas: 3
  template:
    metadata:
      labels:
        app: students-service
    spec:
      containers:
        - name: students-service
          image: thanhnb1/students-service:latest
          envFrom:
            # Thông tin kết nối database thì lấy trong Secret.
            - secretRef:
                name: students-sc

            # Thông tin còn lại thì lấy trong ConfigMap.
            - configMapRef:
                name: students-cm
          ports:
            - containerPort: 8080
      restartPolicy: Always