apiVersion: v1
kind: Pod
metadata:
  name: students-service
  labels:
    app: students-service
spec:
  containers:
    - name: students-service
      image: thanhnb1/students-service:latest
      env:
      - name: SERVER_PORT
        value: "8080"
      - name: MYSQL_URL
        value: "jdbc:mysql://mysql:3306/students"
      - name: MYSQL_USERNAME
        value: "students"
      - name: MYSQL_PASSWORD
        value: "VNTechies2023"
      ports:
        - containerPort: 8080
          name:  http
  restartPolicy: Always