apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-service
  labels:
    app: students-service
spec:
  selector:
    matchLabels:
      app: students-service
  replicas: 3
  template:
    metadata:
      labels:
        app: students-service
    spec:
      containers:
        - name: students-service
          image: thanhnb1/students-service:latest
          ports:
            - containerPort: 8080
          env:
            # Lấy thông tin từ ConfigMap.
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: students-cm
                  key: SERVER_PORT
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: students-cm
                  key: MYSQL_URL

            # Lấy thông tin từ Secret.
            - name: MYSQL_USERNAME
              valueFrom:
                # Lấy biến môi trường từ Secret.
                secretKeyRef:
                  # Tên Secret.
                  name: students-cm
                  # Tên key sẽ lấy được định nghĩa ở phần `data` trong Secret.
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: students-cm
                  key: MYSQL_PASSWORD
      restartPolicy: Always