apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-service
  labels:
    app: students-service
spec:
  selector:
    matchLabels:
      app: students-service
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: students-service
    spec:
      containers:
        - name: students-service
          image: thanhnb1/students-service:v2
          env:
          - name: SERVER_PORT
            value: "8080"
          - name: MYSQL_URL
            value: "jdbc:mysql://mysql:3306/students"
          - name: MYSQL_USERNAME
            value: "students"
          - name: MYSQL_PASSWORD
            value: "VNTechies2023"
          ports:
            - containerPort: 8080
      restartPolicy: Always